# -*- coding: utf-8 -*-
"""Z5_6_rf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E4r-9a_H9M627foaXriHb7LEjKQ3-6kE
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.manifold import TSNE


import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib as mpl

import plotly.express as px
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier

spam = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data")

X = spam.iloc[:,0: 57].values
y =  spam.iloc[: , -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

print(" Accuracy:",metrics.accuracy_score(y_test, y_pred))
print(" Recall:",metrics.recall_score(y_test, y_pred))
print(" Precision:",metrics.precision_score(y_test, y_pred))
f1_score(y_test, y_pred, average='macro')

